### ISSUE TITLE
Error when trying to load git repo

### ISSUE THREAD

**Issue by ddavisso4** [Blakenator/light-git-client#1]
This happens some repos and not others. Hard to provide more info without providing the entire repo.

Console error:
polyfills.c831e7a9c66527c9aa81.js:1 {error: ""}error: ""__proto__: Object
polyfills.c831e7a9c66527c9aa81.js:1 {error: ""}
polyfills.c831e7a9c66527c9aa81.js:1 {error: ""}error: ""__proto__: Object

Nothing logged to standard application logs.

**Comment by Blakenator** [comment]
Error logging was just improved in `v0.5.1`. Turns out all useful properties on plain js errors are not enumerable by default, and therefore don't appear in `JSON.stringify`. Could you please try again and comment the error message?

**Comment by ddavisso4** [comment]
Fixed!
