### ISSUE TITLE
Feature request: tab groups

### ISSUE THREAD

**Issue by flboy1758** [Blakenator/light-git-client#159]
When working with multiple repositories that each have submodules, it would be nice if you could group the parent repo and it's submodules into tab groups for better organization.

**Comment by Blakenator** [comment]
Root problem: hard to differentiate between common submodules across different repos, as all tabs are named the same
Temporary workaround: can rename tabs manually to include repo
Fix: included in #158 , include repo name as prefix when opening submodules in a new tab
